### PR TITLE
:+1: implement options method with class

### PR DESCRIPTION
**Pull request by Milly**
- Improve logic maintainability.
- Minimize code generation logic.
- Reduce the module size. (888KB to 492KB in `option/**`)

## Breaking

This change breaks codes like below.
But I think these can be included in the specifications as unexpected uses.:

```ts
import * as opOld from "jsr:@denops/std@7.1.1/option";
import * as op from "jsr:@denops/std/option";

declare const denops: Denops;

const getDictionaryOld = opOld.dictionary.get;
await getDictionaryOld(denops); // OK

const getDictionaryNew = op.dictionary.get;
await getDictionaryNew(denops); // TypeError: Cannot read properties of undefined (reading '#name')

const getDictionarySafe = op.dictionary.get.bind(op.dictionary);
await getDictionarySafe(denops); // OK
```

```ts
import * as op from "jsr:@denops/std/option";

const options = [
  op.diff,
  op.diffexpr,
];
const localOptions = options.filter(
  (option) => typeof (option as any).getLocal === "function"
); // expected [op.diff] but actual is [op.diff, op.diffexpr]
```

## Summary by CodeRabbit

- **New Features**
	- Introduced a streamlined approach for managing options, enhancing maintainability and clarity.
	- Added specific classes for Boolean, Number, and String options, improving usability.

- **Refactor**
	- Simplified option formatting and instantiation logic, reducing complexity and boilerplate code.
	- Updated option declarations to leverage the new utility classes for a cleaner codebase.

- **Bug Fixes**
	- Enhanced type safety in option management by utilizing TypeScript's type system effectively.

### CODE REVIEW

**Comment by lambdalisue** [comment]
We should avoid breaking changes unless there are significant benefits for both developers and users. However, I believe this PR does not offer enough value for users.

### Pros

- Improve logic maintainability.
- Minimize code generation logic.
- Reduce the module size. (888KB to 492KB in option/**)

### Cons

- Users may access options in an unintended way
  - For example, `winfixwidth` is meant to be window-local, but users can still access it through the `getBuffer` method.

Therefore, I think we should not accept this PR. Did I misunderstand your perspective?

**Comment by Milly** [comment]
> ### Cons
> * Users may access options in an unintended way
>   
>   * For example, `winfixwidth` is meant to be window-local, but users can still access it through the `getBuffer` method.
> 
> Therefore, I think we should not accept this PR. Did I misunderstand your perspective?

There are two problems:
1. `getBuffer()` method exists even though `winfixwidth` etc are "local to window":
   This is an existing problem, [it was there before this PR](https://github.com/vim-denops/deno-denops-std/blob/v7.1.1/option/_generated.ts#L16462).
2. `getLocal()` method etc exists in "global" option:
   This PR's problem.

All methods exist for all options (global or local), but not for the public types.
In other words, any method that is not exposed on the type is said to be `@internal`.
User (developer) can intentionally ignore types to "access options in an unintented way".

```ts
import * as op from "jsr:@denops/std/option";

declare const denops: Denops;

op.ambiwidth.getLocal(denops); // TS2551 [ERROR]: Property 'getLocal' does not exist on type 'GlobalOption<string>'.

(op.ambiwidth as any).getLocal(denops); // No error.
```

**Comment by lambdalisue** [comment]
> getBuffer() method exists even though winfixwidth etc are "local to window":
This is an existing problem, [it was there before this PR](https://github.com/vim-denops/deno-denops-std/blob/v7.1.1/option/_generated.ts#L16462).

Oops. I didn't notice that.

> All methods exist for all options (global or local), but not for the public types.
In other words, any method that is not exposed on the type is said to be @internal.
User (developer) can intentionally ignore types to "access options in an unintented way".

Ah, I see. Then it's OK.

---

So this change is breaking **ONLY** for case 3 right?

### Case 1

```ts
import * as op from "jsr:@denops/std/option";

console.log(await op.ambiwidth.get(denops));
```

### Case 2

```ts
import { ambiwidth } from "jsr:@denops/std/option";

console.log(await ambiwidth.get(denops));
```


### Case 3

```ts
import { ambiwidth } from "jsr:@denops/std/option";

const getAmbiwidth = ambiwidth.get;
//const getAmbiwidth = ambiwidth.get.bind(ambiwidth); // Must be like this
console.log(await getAmbiwidth(denops));
```

**Comment by Milly** [comment]
> So this change is breaking **ONLY** for case 3 right?

> ### Case 3
> ```ts
> import { ambiwidth } from "jsr:@denops/std/option";
> 
> const getAmbiwidth = ambiwidth.get;
> //const getAmbiwidth = ambiwidth.get.bind(ambiwidth); // Must be like this
> console.log(await getAmbiwidth(denops));
> ```

Yes, **ONLY** for case 3 has the breaking change.

**Comment by Milly** [comment]
I'm working #267 and #268 as a continuation of this PR.
But it is a separate issue so I want to meke it a separate PR.

**Review by lambdalisue — APPROVED** [review]

**Pull request merged**
